apiVersion: v1
kind: ConfigMap
metadata:
  name: pal-tracker
  labels:
    app: pal-tracker
data:
  welcome.message: "hello from kubernetes rolling updates"
  management.endpoints: "info,health,palTrackerFailure"
